### ISSUE TITLE
MITOS: Timeout during install 

### ISSUE THREAD

**Issue by menegidio-lab** [galaxyproject/tools-iuc#3698] opened 2021-05-26 23:30 UTC
I need to install Mitos locally and I see the error below:

(1/9) Installing repository mitos from iuc to section "annotate-mito" at revision f86bcffa9549 (TRT: 0:00:07.556675)
Timeout during install of mitos, extending wait to 1h

This error is seen for Mitos and Mitos2, however, other tools install normally. The error is viewed by both the server https://toolshed.g2.bx.psu.edu and https://testtoolshed.g2.bx.psu.edu

I've been trying to install for two consecutive days. I will need the tool for a workshop.

Currently the settings are:

api_key: admin
galaxy_instance: http: // localhost: 8080
install_repository_dependencies: True
install_resolver_dependencies: True
install_tool_dependencies: True
tools:

- name: mitos
   owner: iuc
   tool_panel_section_id: 'annotate-mito'
   tool_shed_url: https://toolshed.g2.bx.psu.edu/

- name: mitos2
   owner: iuc
   tool_panel_section_id: 'annotate-mito'
   tool_shed_url: https://toolshed.g2.bx.psu.edu

**Comment by bernt-matthias** [comment] 2021-05-29 09:24
Can you try to install manually in the Galaxy UI?

**Comment by bernt-matthias** [comment] 2021-05-30 07:53
Duplicate of https://github.com/bgruening/galaxytools/issues/1124

**Closed by bernt-matthias** 2021-05-30 07:53 UTC
