### ISSUE TITLE
bioperl script missing packages, probably

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#380] opened 2015-11-10 01:48 UTC
Moved stuff to a new server where only bioperl was installed, jobs failed when trying to run that tool. Seems to need:
- Pod::Usage
- YAML
- LWP::UserAgent

**Comment by lparsons** [comment] 2016-04-26 14:00
Duplicate of #659

**Closed** 2018-09-06 07:58 UTC
Labels: bug, won't fix - tool_dependencies.xml
