### ISSUE TITLE
IUC Contribution Fest - RADSeq Tools and Workflows

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#422] opened 2015-11-27 21:07 UTC
We are planning a Remote Contribution Fest on **7th and 8th of March** for developers to work on Galaxy RADSeq tools.

RADSeq is a cheap sequencing technology that is used by many resource-limited groups who would benefit a lot from easy-to-use galaxy tools. Indeed there has been quite some interest in analyzing RADSeq with Galaxy. Currently there is a wrapper for stacks and little more to help with RAD specific analysis (though many other galaxy tools are useful with RADs - bwa, cap3, gatk, velvet, ...).

If you are interested in participating in the hackathon but not interested in actual tool development - we will assemble a list of smaller, manageable Python and JavaScript tasks to work on and certainly documentation is a chronically lacking for collections so we could use help there and no actual coding would be required.

We encourage ideas or advice about how to organize this so please let us know. A core group will be available on IRC all day and we will have google hangouts across those days to organize, answer questions, and report progress.

We will do our best to coordinate and make this hackathon a nice and productive experience and we would like to especially focus on working reasonable hours and discourage overnighters.

**All forms of contribution are welcome!**

Google hangout link for the hackathon:
https://hangouts.google.com/call/iiksaostt5dwfms4lph6nuj74ye

Original idea from @bgruening (galaxyproject/tools-devteam#26 (comment)). See #299 and #239 for information on the last two hackathons. This text is inspired on #299.
## Things to work on

This list will be updated as comments are made on the issue. Your are strongly encouraged to leave your suggestion/opinion/criticism below.

Note that while the list is currently stacks-oriented, there is no reason for that to be the final list of stuff to do... **Non-stacks based suggestions are strongly encouraged**
- Existing stacks plugin (https://github.com/genouest/galaxy-tools/tree/master/tools/stacks)
  - Support for data collections
  - cap3 integration
  - support multi-threading (GALAXY_SLOTS)
  - upgrade the version of stacks
  - support clone_filter
- Implement stacks workflows
- Check the feasibility of implementing the stacks web interface on Galaxy
- have a process_radtags alike with a configurable enzyme sequence (i.e allow demultiplexing using a configurable sequence)
- [PyRAD](https://github.com/dereneaton/pyrad)
- [dDocent](https://github.com/jpuritz/dDocent) 
## Reading list
- [Stacks homepage](http://catchenlab.life.illinois.edu/stacks/)
- [Population Genomics of Parallel Adaptation in Threespine Stickleback using Sequenced RAD Tags](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1000862)
- [Analyse de données RADseq sous Galaxy : l'exemple de STACKS](https://www.e-biogenouest.org/resources/1321) - In French from @yvanlebras
- [PyRAD documentation](http://nbviewer.ipython.org/gist/dereneaton/af9548ea0e94bff99aa0/pyRAD_v.3.0.ipynb) - Jupyter notebook

**Comment by bgruening** [comment] 2015-11-29 17:50
Just wanted to say that this is awesome! I'm in and try to help wherever I can!

**Comment by abretaud** [comment] 2015-12-01 14:14
Writing wrappers for [PyRAD](https://github.com/dereneaton/pyrad) or [dDocent](https://github.com/jpuritz/dDocent) would be cool too

**Comment by bgruening** [comment] 2015-12-01 14:37
@abretaud I added them to the list, thanks!

**Comment by tiagoantao** [comment] 2015-12-01 19:17
@bgruening @abretaud I have added a link to PyRad documentation. I will probably send an email to the author to see if he wants to participate. He is a Python programmer, so he might be interested...

**Comment by tiagoantao** [comment] 2016-01-05 15:42
@abretaud @bgruening @yvanlebras It is now new year and the metagenomics fest is long gone. I was thinking in resurrecting this in the next few days (start preparing, finding potential volunteers, ...)

**Comment by abretaud** [comment] 2016-01-07 10:57
Hi (and happy new year!)
It looks like a good idea! It's not really clear for me yet what we will be needed for the stacks web interface (i.e. potential IE). I don't have much time these days to look into it, but it would good to think about it before the hackathon

**Comment by tiagoantao** [comment] 2016-01-10 16:52
@abretaud There is a stacks package as you probably know http://toolshed.genouest.org/repos/cmonjeau/stacks . This was developed by @yvanlebras and @cmonjeau .

I am making a few changes myself (which I can make public), namely:

- Support for GALAXY_SLOTS (multi-threading)
- Support for collections
- General version upgrade of tools

I had a local request for supporting clone_filter, which I can work on.

With regards to this plugin, @yvanlebras, you would consider accepting patches? And maybe put it under tools-uic?

**Comment by yvanlebras** [comment] 2016-01-10 17:01
Hi @tiagoantao,

For sure we will accept patches and put it under tools-iuc ! We will exchange locally in Rennes with @abretaud and @cmonjeau to prepare our participation to this contribution fest.

**Comment by tiagoantao** [comment] 2016-01-10 17:06
@yvanlebras Any possibility you would put the code on github (even if not under tools-iuc)? I could submit a PR against it.

**Comment by yvanlebras** [comment] 2016-01-10 17:19
@tiagoantao of course! I have to check with @cmonjeau, because I see only these 1.18 stacks tools even if we have a more recent 1.32 one..... I will keep you informed!

**Comment by yvanlebras** [comment] 2016-01-10 17:22
.....@tiagoantao I forgot the hyperlink: https://github.com/genouest/galaxy-tools/tree/master/tools/stacks

**Comment by tiagoantao** [comment] 2016-01-10 17:33
@yvanlebras In my version, I have upgraded all the tools. I will start submitting PRs today.

**Comment by yvanlebras** [comment] 2016-01-10 17:36
@tiagoantao Thanks! OK,  I will have a look.

**Comment by yvanlebras** [comment] 2016-01-29 23:03
With @lecorguille, Maria Bernard and @abretaud, we begin to create things like remote hackathon dedicated [Trello](https://trello.com/b/EfGYBOPX/hackthon-radseq) and [HUBzero space](https://cesgo.genouest.org/groups/guggo/wiki/RADseqHackathon to prepare the event.

**Comment by tiagoantao** [comment] 2016-01-29 23:15
I had a request for rapture support:
http://genetics.org/content/early/2015/12/22/genetics.115.183665

**Comment by tiagoantao** [comment] 2016-02-05 00:26
I am going to drop an email to the authors of PyRad and dDocent about our hackthon

**Comment by yvanlebras** [comment] 2016-02-05 00:43
Hi Tiago, 

Good idea! 

I cc Julian concerning Stacks ! 

Here in France, we begin to prepare the event ! A preliminary description is written on our GUGGO Galaxy working group dedicated space ( https://cesgo.genouest.org/groups/guggo/wiki/RADseqHackathon ). 

Don't hesitate to come back to us if we can help ! 

Cheers, 

Yvan 

----- Mail original -----

> De: "Tiago Antao" <notifications@github.com>
> À: "galaxyproject/tools-iuc" <tools-iuc@noreply.github.com>
> Cc: "yvanlebras" <yvan.le_bras@irisa.fr>
> Envoyé: Vendredi 5 Février 2016 01:26:26
> Objet: Re: [tools-iuc] IUC Contribution Fest - RADSeq Tools and Workflows
> (#422)

> I am going to drop an email to the authors of PyRad and dDocent about our
> hackthon

> —
> Reply to this email directly or view it on GitHub .

-- 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Yvan Le Bras, PhD @Yvan2935 <°))))>< 
e-Biogenouest project http://www.e-biogenouest.org 
CNRS UMR 6074 IRISA-INRIA, Campus de Beaulieu, 35042 Rennes Cedex 
tél.: +33 (0) 2 99 84 71 79 / +33 (0) 6.10.43.96.51 
yvan.le_bras@irisa.fr

**Comment by jpuritz** [comment] 2016-02-07 16:39
Hi everyone,

I'm happy to help with implementing dDocent and filtering scripts!

Thanks for including dDocent.

**Comment by abretaud** [comment] 2016-02-24 10:55
@bgruening I have seen some PR about a migration to conda to define tool dependencies: for this hackathon do you think we should use this new method or is it better to stick to the good-old tool_dependencies.xm method?
In the first case, is there some guide/documentation/howto that we could use?

**Comment by bgruening** [comment] 2016-02-29 18:54
@abretaud yes we should. I will help as much as I can. This will save us so much time and provides us with free testing.

**Comment by abretaud** [comment] 2016-03-01 08:38
All right, I'm preparing a few slides to introduce this on monday

**Comment by bgruening** [comment] 2016-03-01 08:47
Uh awesome - let me know if you have any questions and if I should prep some packages for monday and get it into bioconda.

**Comment by abretaud** [comment] 2016-03-01 13:12
As there is a long todo list for stacks, maybe having it in bioconda before the hackathon would help, if you have some time to do it?

**Comment by tiagoantao** [comment] 2016-03-01 13:18
I can do the stacks on bioconda

**Comment by abretaud** [comment] 2016-03-01 13:21
Great, thanks!

**Comment by tiagoantao** [comment] 2016-03-03 01:36
I have added this to bioconda as a PR, while I can merge it, I would prefer @bgruening to have a look.

here: https://github.com/bioconda/bioconda-recipes/pull/925

**Comment by yvanlebras** [comment] 2016-03-04 08:20
@cmonjeau have made PR for pyrad and mawk bioconda. If you can also have a look @bgruening ;)
[mawk bioconda recipes](https://github.com/bioconda/bioconda-recipes/pull/929)
[pyRAD bioconda recipes](https://github.com/bioconda/bioconda-recipes/pull/928)

**Comment by bgruening** [comment] 2016-03-04 08:31
You all rock! This will be a fantastic hackathon with conda dependencies and travis testing all at once!
I commented on the PR!

**Comment by Eduardo-Alves** [comment] 2016-03-04 14:08
Hi, has anyone started looking into "the feasibility of implementing the stacks web interface on Galaxy". I started looking into visualization plugins using mako but I believe there must be a way to do it with JSON/Backbone. Anyone has some pointers? I am happy to help!

**Comment by abretaud** [comment] 2016-03-04 14:14
I was thinking about working on an interactive environment for stacks.
IIRC the web interface allow to modify the data, so using IE looks like the perfect solution for this (ie load the stacks preliminary results in the IE, make changes to it if you want, and then inject the corrected data to your history)

I'll see next week if I have time to work on this during the hackathon, but your help is very welcome anyhow!

**Comment by Eduardo-Alves** [comment] 2016-03-04 14:52
Anthony,

The only update I can see in the web interface is to add an annotation, which is probably saved to the mysql database.  I haven't developed IE, do you mean creating an apache IE and using the existing web interface? Can you add a mySQL database to an IE?

**Comment by bgruening** [comment] 2016-03-04 15:42
@Eduardo-Alves you can add anything to an IE. For example we have a RStudio IE or a Jupyter/IPython IE.

**Comment by yvanlebras** [comment] 2016-03-04 15:52
Our @abretaud original idea ;) was to use the existing Stacks Galaxy tools, who don't use the STACKS database and thus don't propose the Stacks web interface based on the database (if I'm not wrong...), to produce results and then, "reconstruct" a database who will (maybe) give the possibility to create the Stacks web interface...... One idea is to use the quite recently developped [load_radtags.pl](http://catchenlab.life.illinois.edu/stacks/comp/load_radtags.php) Stacks script to take Galaxy tools results (for exemple an archive from denovo_map) and create the database on a IE where we can interact with this db from the classical Stacks web interface....

**Comment by Eduardo-Alves** [comment] 2016-03-04 15:56
Anthony, 

Wouldn't implementing it as an IE restrict it instances where the admin is capable of setting it up?  
I think a plugin might be harder to implement but visualizations will be installable from toolshed in version 16.04
https://github.com/galaxyproject/galaxy/issues/1191

**Comment by Eduardo-Alves** [comment] 2016-03-04 16:11
@yvanlebras do you have any screenshots examples of the manual correction of the genotypes in the web interface? all I can see is the annotate link 
http://gbs-cloud-tutorial.readthedocs.org/en/latest/_images/stacks_web_database.png

**Comment by yvanlebras** [comment] 2016-03-04 16:31
@Eduardo-Alves there is things like [that](http://images.google.fr/imgres?imgurl=http%3A%2F%2Fcatchenlab.life.illinois.edu%2Fstacks%2Fimages%2Fss%2Fmap_markers_ss.png&imgrefurl=http%3A%2F%2Fcatchenlab.life.illinois.edu%2Fstacks%2F&h=805&w=1050&tbnid=nMB2AxbsyY80oM%3A&docid=UI2zoKZCEjVWWM&ei=_bfZVsiKLImMUcirpIAC&tbm=isch&iact=rc&uact=3&dur=955&page=1&start=0&ndsp=53&ved=0ahUKEwiI_ez9uafLAhUJRhQKHcgVCSAQrQMIIzAC)

**Comment by Eduardo-Alves** [comment] 2016-03-04 16:43
@yvanlebras yes, that's the screenshot I sent you. It is just displaying the results, not modifying. The only think you can add is an annotation.  
My suggestion is to use the existing stacks tool to generate the raw data, then load it to a sqllite database which is single user and doesn't require setup like mysql and then generate the web interface using mako template.  In this way it can be published as a plugin and will be installable from toolshed.

**Comment by bgruening** [comment] 2016-03-05 11:07
I just opened a google hangout https://hangouts.google.com/call/iiksaostt5dwfms4lph6nuj74ye that we can use on Monday. I will be around from 10.00 MEZ and help wherever I can.

**Comment by yvanlebras** [comment] 2016-03-05 12:55
Thanks Björn ! 
We will begin at 10h30 Rennes time. I will try to go back to you before to give you more informations on what we plan to do. For now, it appears positions like :-Maria Bernard and Gildas Le Corguillé will work on the implementation of some in-house Stacks post-process scripts-Cyril Monjeaud will be a mentor for docker / conda related tasks + work on the creation of dDocent Galaxy tools-Anthony Bretaudeau will be a mentor for conda related tasks + work on IE for Stacks-others Rennes people will work on dependencies / conda / dockerfiles writing ...
Maybe Tiago is interested by updating Galaxy tools (with Gildas maybe)
What about PyRAD?
Wishing you a good week end. 
Yvan 

-------- Message d'origine --------
De : Björn Grüning <notifications@github.com> 
Date : 05/03/2016  12:07  (GMT+01:00) 
À : galaxyproject/tools-iuc <tools-iuc@noreply.github.com> 
Cc : yvanlebras <yvan.le_bras@irisa.fr> 
Objet : Re: [tools-iuc] IUC Contribution Fest - RADSeq Tools and Workflows (#422) 

I just opened a google hangout https://hangouts.google.com/call/iiksaostt5dwfms4lph6nuj74ye that we can use on Monday. I will be around from 10.00 MEZ and help wherever I can.


---

**Comment by bgruening** [comment] 2016-03-06 19:19
Hi!

unfortunately, I need to attend a meeting tomorrow and only will be available from 15.00 MEZ :)

I created a few branches and we have for most of the tools already conda packages that can be reused. This hopefully means we do not need to spend time to create tool_dependencies or install a particular version - and gives us more time to improve the wrappers.

pyrad: https://github.com/galaxyproject/tools-iuc/pull/646
ddocent: https://github.com/galaxyproject/tools-iuc/pull/647
stacks: https://github.com/galaxyproject/tools-iuc/pull/648
mixed radseq: https://github.com/galaxyproject/tools-iuc/pull/649

Would be great if we can use these branches tomorrow. The IUC will merge as often as possible into these branches so we can synchronise our work in these branches and distribute the work.
Does this sounds like a plan?

We can coordinate our work via a google hangout:

https://hangouts.google.com/call/iiksaostt5dwfms4lph6nuj74ye 
or
IRC #galaxyproject on freenode

With a little bit luck we will also have some contributes that want to focus on usability aspect of our tools, including documentation. It would be nice if we can introduce them to use the github webinterface to contribute help text or similar things like an example workflow.
For example this could be used to create a nice help text for PyRad: http://rst.ninjs.org

Thanks and sorry for joining so late,
Bjoern

**Comment by tiagoantao** [comment] 2016-03-07 01:16
I am currently in Europe (UK) and will be joining around 10 WET (that is 11 in France/Germany).

I will be working on mostly two things: i) cap3 integration with stacks and ii)rapture.
I do have a few remaining patches for the stacks tool (though mostly were already integrated) - but it will not be my main focus.

**Comment by yvanlebras** [comment] 2016-03-07 07:23
Thanks @tiagoantao for these details ! We thus maybe can propose to find someone today to update Stacks to the 1.37 version, support for data collection and support Galaxy_SLOTS.

**Comment by yvanlebras** [comment] 2016-03-07 07:28
Hi everyone, as we will make some introductions (planemo/bioconda, Diocker, RADseq) this morning for french people, you can access the presentations slides on the [GUGGO dedicated pages](https://cesgo.genouest.org/tags/galhackradfr)

**Comment by Eduardo-Alves** [comment] 2016-03-07 09:37
Bon jour! Will the introductions going to be also on hangouts?

**Comment by tiagoantao** [comment] 2016-03-07 10:11
@yvanlebras : 1.37 and GALAXY_SLOTS were already included, in the github version. they are ready!

**Comment by tiagoantao** [comment] 2016-03-07 10:13
There was nobody on the hangouts. when somebody logs in, just write here and I will be joining also. I am working on cap3 for now.

**Comment by mvdbeek** [comment] 2016-03-07 10:16
@tiagoantao there is already a cap3 wrapper in the toolshed:
https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_cap3
we can include it in the iuc, if that's preferable.

**Comment by tiagoantao** [comment] 2016-03-07 10:18
@mvdbeek  I know but it does not work well with stacks

**Comment by mvdbeek** [comment] 2016-03-07 10:21
what does not work well? can it be improved ?
just trying to avoid duplicate efforts.

**Comment by tiagoantao** [comment] 2016-03-07 10:23
There is a script called exec_velvet.pl in stacks that uses velvet. We
would like it to use cap3. There is probably no need to make a new tool
(evaluating that), just integrating them.

On 7 March 2016 at 03:21, Marius van den Beek <notifications@github.com>
wrote:

> what does not work well? can it be improved ?
> just trying to avoid duplicate efforts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/issues/422#issuecomment-193194650>
> .
>



-- 
"While I may be sending this email outside my normal office hours, I have
no expectation to receive a reply outside yours" - @tomstafford

**Comment by tiagoantao** [comment] 2016-03-07 10:28
@mvdbeek would you think it would make sense to have a bioconda version of cap3?

**Comment by tiagoantao** [comment] 2016-03-07 10:35
@mvdbeek Please ignore my idea, cap3 seems to have a non-free license. I will be using your packages directly and not worry with bioconda

**Comment by mvdbeek** [comment] 2016-03-07 10:38
> There is a script called exec_velvet.pl in stacks that uses velvet. We
> would like it to use cap3. There is probably no need to make a new tool
> (evaluating that), just integrating them.

okay I see! 

> Please ignore my idea, cap3 seems to have a non-free license. I will be using your packages directly and not worry with bioconda

Ah, yes, we'll need to display that license on our package ;/

**Comment by tiagoantao** [comment] 2016-03-07 10:46
@yvanlebras Another PR for stacks can be found here: https://github.com/genouest/galaxy-tools/pull/4

**Comment by yvanlebras** [comment] 2016-03-07 11:01
Thanks! We will hangout this afternoon....


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Tiago Antao <notifications@github.com> 
Date : 07/03/2016  11:46  (GMT+01:00) 
À : galaxyproject/tools-iuc <tools-iuc@noreply.github.com> 
Cc : yvanlebras <yvan.le_bras@irisa.fr> 
Objet : Re: [tools-iuc] IUC Contribution Fest - RADSeq Tools and Workflows (#422) 

@yvanlebras Another PR for stacks can be found here: genouest/galaxy-tools#4

**Comment by tiagoantao** [comment] 2016-03-07 13:01
I just merged stacks support in bioconda

**Comment by bgruening** [comment] 2016-03-07 14:38
@tiagoantao awesome! I'm now in and try to review PR :)

**Comment by bgruening** [comment] 2016-03-07 14:56
@tiagoantao we are now in the hangout. Also here is a Trello board: https://trello.com/b/EfGYBOPX/hackthon-radseq

**Comment by tiagoantao** [comment] 2016-03-07 15:35
@yvanlebras / @bgruening   Question: the current correct place to work on the stacks tool is:
https://github.com/galaxyproject/tools-iuc/tree/stacks
Not the old:
https://github.com/genouest/galaxy-tools
correct?

I am going to work on cap3 on whatever repo you tell me to...

**Comment by abretaud** [comment] 2016-03-07 15:36
Yes that's it, no more work on genouest github now

**Comment by tiagoantao** [comment] 2016-03-07 15:38
@abretaud thanks!

**Comment by yvanlebras** [comment] 2016-03-07 16:42
Is it a way @jpuritz to help us implementing dDocent ? If we well understood, the user normally have to follow "the text based prompts". Which way you think is the best to integrate dDocent in Galaxy ?

**Comment by bgruening** [comment] 2016-03-07 16:49
@yvanlebras here is a Docker pyrad container. Automatically created with conda packages.
`docker run -it --rm quay.io/mulled/pyrad:3.0.64--py27_0`

**Comment by yvanlebras** [comment] 2016-03-07 17:45
Is it a way @jpuritz to help us implementing dDocent ? If we well understood, the user normally have to follow "the text based prompts". Which way you think is the best to integrate dDocent in Galaxy ?

**Comment by yvanlebras** [comment] 2016-03-08 05:59
Sorry Eduardo, I miss your e-mail... 
As the introduction speechs were in english, hangout was not used but presentation slides are here: https://cesgo.genouest.org/tags/galhackradfr
Wishing you a good day.
Yvan
Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Eduardo de Paiva Alves <notifications@github.com> 
Date : 07/03/2016  10:37  (GMT+01:00) 
À : galaxyproject/tools-iuc <tools-iuc@noreply.github.com> 
Cc : yvanlebras <yvan.le_bras@irisa.fr> 
Objet : Re: [tools-iuc] IUC Contribution Fest - RADSeq Tools and Workflows (#422) 

Bon jour! Will the introductions going to be also on hangouts?


---

**Comment by bgruening** [comment] 2016-03-08 11:55
@yvanlebras what do you mean here?

**Comment by yvanlebras** [comment] 2016-03-08 13:29
@bgruening concerning our presentations of tomorrow morning ? We made it in French, so we have not used hangout to avoid proposing "english speaking" colleagues to hear us speaking french.....

**Comment by bgruening** [comment] 2016-03-08 13:35
Uh, I was referring to an other comment of you that disappeared. Never mind.
We should all learn Esperanto ;)

**Comment by yvanlebras** [comment] 2016-03-08 13:35
+1 ;) or deutsch !

**Comment by Eduardo-Alves** [comment] 2016-03-08 13:39
I speak french! But its' ok, I  had the slides so I read them instead of
the hangout.


Eduardo

**Comment by tiagoantao** [comment] 2016-03-08 14:30
@yvanlebras et al: Are you planning to add any test data snippet to the stacks tool? For automated testing purposes.

If you have something to test STACKS_sort_read_pairs , I could re-use it with my version without velvet...

**Comment by tiagoantao** [comment] 2016-03-08 14:32
Sorry, closed by mistake...

**Comment by yvanlebras** [comment] 2016-03-08 14:36
Yes, for sure! For sort_read_pairs, you can use the original STACKS sample data : http://catchenlab.life.illinois.edu/stacks/pe_tutorial/pe_samples.tar.gz

**Comment by yvanlebras** [comment] 2016-03-08 14:37
For other STACKS scripts, I propose some datasets [here](https://cesgo.genouest.org/groups/guggo/collections/stacks-sample-datasets)

**Comment by tiagoantao** [comment] 2016-03-08 14:49
@yvanlebras thanks!

**Comment by tiagoantao** [comment] 2016-03-08 14:52
@yvanlebras Just one thing: we might have to add some of these to the tool in order to have automated testing...

**Comment by yvanlebras** [comment] 2016-03-08 14:57
@tiagoantao Yes, of course! ;) we are adding data for each tools to enable functional testing...

**Comment by bgruening** [comment] 2016-03-08 14:59
@tiagoantao we are on it in the latest PR. The problem is that we encountered a few planemo/tools issues we need to sort out. But we are working on it.

**Comment by yvanlebras** [comment] 2016-03-08 17:52
In France, we don't have anything to ea

A preliminary report of our participation: http://cesgo.genouest.org/groups/guggo/wiki/RADseqHackathon

**Comment by bgruening** [comment] 2016-03-08 18:02
Thanks a lot @yvanlebras + team! Keep the PR coming!

**Comment by tiagoantao** [comment] 2016-03-08 19:11
When do you guys think the new stacks version will hit the toolshed? Selfish-me here talking, I would like to install it ASAP. ;)

I am finalizing the sort_pair_reads / velvet decoupling, but that can go later...

**Comment by abretaud** [comment] 2016-03-09 08:20
There is quite some work left to do, personally I will continue to work on this in the coming weeks, but after a week of holidays ;)

**Comment by lecorguille** [comment] 2016-03-09 08:53
@yvanlebras <https://github.com/yvanlebras> The dataset, you produce for
ref_map, is a little poor. I get empty tsv (
https://github.com/galaxyproject/tools-iuc/tree/stacks/tools/stacks/test-data).
Or perhaps I'm to strong in my parameters (population with -n 3 -m 1)

2016-03-09 9:20 GMT+01:00 Anthony Bretaudeau <notifications@github.com>:

**Comment by yvanlebras** [comment] 2016-03-09 09:02
This is not your parameters, only the data who are poor, you're right. If you need something who generates not empty file for this last population step, I need some additional time ;) I will try today... Thanks for pointing this!


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Gildas Le Corguillé <notifications@github.com> 
Date : 09/03/2016  09:53  (GMT+01:00) 
À : galaxyproject/tools-iuc <tools-iuc@noreply.github.com> 
Cc : yvanlebras <yvan.le_bras@irisa.fr> 
Objet : Re: [tools-iuc] IUC Contribution Fest - RADSeq Tools and Workflows (#422) 

@yvanlebras <https://github.com/yvanlebras> The dataset, you produce for
ref_map, is a little poor. I get empty tsv (
https://github.com/galaxyproject/tools-iuc/tree/stacks/tools/stacks/test-data).
Or perhaps I'm to strong in my parameters (population with -n 3 -m 1)

2016-03-09 9:20 GMT+01:00 Anthony Bretaudeau <notifications@github.com>:

> There is quite some work left to do, personally I will continue to work on
> this in the coming weeks, but after a week of holidays ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/issues/422#issuecomment-194178656>
> .
>


---

**Comment by tiagoantao** [comment] 2016-03-09 16:19
If it takes some time, then I will soon submit a PR with the sort_read_pairs decoupling

**Comment by martenson** [comment] 2017-02-23 16:02
Closing this issue since this codefest is long finished. Thanks all!

**Closed by martenson** 2017-02-23 16:02 UTC
