### ISSUE TITLE
Project "Conda migration"

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#522] opened 2016-01-08 22:10 UTC
As a few of you already know I have spend a few days to mass migrate TS packages to the conda build system. The aim was to simple deactivate the current TS dependency resolver and use the conda resolver instead ... a mid-term aim, I admit :)

The good news is that I was able to migrate a lot of our IUC packages in two days and uploaded them to [bioconda](https://github.com/bioconda/bioconda-recipes), a community maintained project (called conda channel). They are now alive and you can try them in Galaxy today :)
I created a migration script from tool_dependencies.xml files to conda recipes based on @peterjc work. It is really messy because of so many exceptions and it does not work 100%. Nevertheless is saves a lot of time and generates nice recipes. It is actually fun to finally come up with tests and use them to test packages.

Here it is: https://github.com/bgruening/planemo/tree/conda

Basic packages like zlib, cairo etc. are already in conda, so less work and a really nice system to test dependencies as you probably all now, so this is a huge win.

I encountered a few problems I want to discuss with you before I try to migrate the rest of IUC and devteam.
## 1. namespaces

We have some wired package names, like `python_pillow` which should be `pillow` and is so in conda. But also some more subtle things like rnastar -> star or vienna_rna -> viennarna is a problem, Moreover, package names with dash ala `12-2013` are not allowed in conda.

Namespace issue, but hey this was expected isn't it? The good part is that I guess 80% of all dependencies will just work if you switch your dependency resolver to conda. To get the other 20% working we need to find a solution. I see two possibilies:
Please let me know what you think
- For recent tools change include a new <requirement> tag with the new name in addition to the old one. Galaxy will try as long as one name fits.
- For old tools we can not do this any ideas here?
- We could have a global galaxy namespace mapping file, for example `vienna_rna -> viennarna`
- We do not care as much as old tools needs to use the old backend.
## 2. versioning and sustainability

The second and bigger problem is again about versioning, archiving and sustainability. As Galaxy project we have a strong commitment to reproducibility, this means archiving packages and keeping strict versioning. See our projects like [cargo-port](https://github.com/galaxyproject/cargo-port), [bioaRchive](https://bioarchive.galaxyproject.org) which is actually used by bioconda :)! or Galaxy own dependency resolver. In theory this is also easily possible in conda! Nevertheless as we all know this is hard and takes resources. 

For example R2 versions are currently not available in conda. There are a few R3 versions in the main conda channel, but not all which we need. 
We can create some, as done [here](https://github.com/bgruening/conda-recipes/tree/old_R) but it is unlikely to get them into the main channel. I had hoped that bioconda would be a possibility and I'm currently discussing this problem [here](https://github.com/bioconda/bioconda-recipes/pull/574).
As it stands bioconda wants to go with the most recent version and I'm sorry that I added so many older packages over the last days. It also seems that strict version dependency is not seen as necessary which kind of kills my effort to bring our packages 1to1 to bioconda.

Read more here: https://github.com/bioconda/bioconda-recipes/pull/574

So what does this mean for us? 
Do we want to have a strict version dependency in the conda backend? Even in the case that this means that we need to have our own channel? Anaconda repositories are limited in space so we probably need to get in contact with them or we need to to find an other solution.

I really had hoped to get our stuff in bioconda and join forces here, but with our focus on reproducibility it seems we are kind of isolated :(

Please let me know what you think and how you envision the future of package management in the Galaxy eco system.

**Comment by erasche** [comment] 2016-01-08 23:21
awesome stuff @bgruening :) Sincerely, thank you for putting the effort into getting these discussions and efforts going.

> unlikely to get them into the main channel

I don't see this as a problem, we should have our own galaxy channel which we dump all of the old crap into that no one (i.e. bioconda, r) wants to deal with. We can have as strict of versions as we want.

> Anaconda repositories are limited in space 

self hosting is easy. We could do it on depot. I'd say we *start* self hosting, and not even think about anaconda's official ones. We should be *able* to create conda packages for all of bioarchive automatically, not worrying about running out of space. (Of course, we should not, just the ones that are actually useful)

> I really had hoped to get our stuff in bioconda and join forces here 

will it be any easier going forward? With new packages? Or do they really not care about strict versioning?

**Comment by mvdbeek** [comment] 2016-01-09 08:46
This looks super-interesting and the build-tests will be a huge win!
I guess the only step forward is trying, if you think that conda is as close to feaure-complete as it gets.
- Will we be able to support packages by different owners?
- Would this require users to setup their own channel? 
- What would be the procedure to quickly test a new conda recipe?
I like the fact that every tool developer has easy and (kind of) unlimited access to the toolshed, so I think we should be aiming for a similar resource to keep the transitioning barrier low.

Maybe some of the points

**Comment by bgruening** [comment] 2016-01-09 12:32
>> unlikely to get them into the main channel

>I don't see this as a problem, we should have our own galaxy channel which we dump all of the old crap into that no one (i.e. bioconda, r) wants to deal with. We can have as strict of versions as we want.

We can do this. But we need to get all on board I guess and integrate it deeply with bioaRchigve and cargo-port.

>> Anaconda repositories are limited in space 

> self hosting is easy. We could do it on depot. I'd say we *start* self hosting, and not even think about anaconda's official ones. We should be *able* to create conda packages for all of bioarchive automatically, not worrying about running out of space. (Of course, we should not, just the ones that are actually useful)

Hehe, see here: "If conda can handle such cases I guess it would be easier for us to integrate this directly into bioaRchive instead of doing this on demand on pushing regularly to bioconda." from https://github.com/bioconda/bioconda-recipes/pull/574#issuecomment-170072824 :)


>> I really had hoped to get our stuff in bioconda and join forces here 

> will it be any easier going forward? With new packages? Or do they really not care about strict versioning?

They are not really aware of the problem I guess. Or we are just to radical.
We have a lot of binaries, e.g starforge can be more or less replaced by conda if we do it right and at least this can/should be shared with bioconda. In the end it does not matter if we activate 3 or 4 channels by default. What I really like to avoid is to just recreate recipes because we have a more strict police. 

@mvdbeek 

> This looks super-interesting and the build-tests will be a huge win!
I guess the only step forward is trying, if you think that conda is as close to feaure-complete as it gets.
- Will we be able to support packages by different owners? (Or is this concept obsolete now?)

This concept is obsolete know and is replaced by channels. Channels do fit the IUC group and you can move recipes between channels without any hassle. So if one channel disappears we should be able to create a new one and put all recipes back in.

- Would this require users to setup their own channel? 

Yes, or contribute to the IUC, bioconda channel. I would vote for collecting recipes (as we do now) in one channel.

- What would be the procedure to quickly test a new conda recipe?

Assuming you have defined tests ...
```
conda build bowtie2
```

> I like the fact that every tool developer has easy and (kind of) unlimited access to the toolshed, so I think we should be aiming for a similar resource to keep the transitioning barrier low.

Hehe, unlimited it is only because the Galaxy project is paying. Bioconda is now depended on continuum and has 100GB afaik - and this is a special offer usually you get 3GB.

> Maybe some of the points will be clear once I tried the new stuff.
Also in-the-face docs would be good, I have certainly read @gregvonkuster [blog entry](http://gregvonkuster.org/galaxy-tool-shed-framework-building-galaxy-tools/) tens of times.

I'm volunteering to write such things and include it into the best practice IUC repository as soon as it is more clear how do we want to proceed here. A dedicated hackathon would be also nice. Most of my porting time is spend in compiling and writing tests, so I could need help here :)

That said this is not super urgent as we can only rely on conda builds if Galaxy 16.01 is on most installations, but we could work the infrastructure behind this in the meantime and get some Docker-Conda only containers running :)

**Comment by erasche** [comment] 2016-01-09 16:27
> We can do this. But we need to get all on board I guess and integrate it deeply with bioaRchigve and cargo-port.

I think everyone is on board, judging by comments I've read. I don't know about the "deep integrations", we can figure out some of that later. cargo-port is feature complete, it is just a dumb tarball store, that's it. bioaRchive has room for features, so maybe there's work to be done there.

> Hehe, see here: "If conda can handle such cases I guess it would be easier for us to integrate this directly into bioaRchive instead of doing this on demand on pushing regularly to bioconda." from bioconda/bioconda-recipes#574 (comment) :)

I'm not understanding why you're pushing bioaRchive integration so much -- we do so much more than just R packages. If you want packages in a conda repo, we should set up hooks in bioaRchive to automatically push packages to the conda repo, but maybe this is what you meant.

> They are not really aware of the problem I guess. Or we are just to radical.

hah, ok.

> We have a lot of binaries, e.g starforge can be more or less replaced by conda if we do it right and at least this can/should be shared with bioconda. In the end it does not matter if we activate 3 or 4 channels by default. What I really like to avoid is to just recreate recipes because we have a more strict police.

sure, understood, agreed.

> I'm volunteering to write such things and include it into the best practice IUC repository as soon as it is more clear how do we want to proceed here. A dedicated hackathon would be also nice. Most of my porting time is spend in compiling and writing tests, so I could need help here :)

happy to help @bgruening, just assign me issues :)

**Comment by bgruening** [comment] 2016-01-09 17:20
> I'm not understanding why you're pushing bioaRchive integration so much -- we do so much more than just R packages. If you want packages in a conda repo, we should set up hooks in bioaRchive to automatically push packages to the conda repo, but maybe this is what you meant.

Bioconda is using it and they know it. All of our other projects probably not, it was serving as an example because the discussion there started with an R PR.
And yes this is exactly what I meant. Remember this PR https://github.com/bioarchive/aRchive_source_code/pull/20, I will extend it to spit out conda recipes.

**Comment by erasche** [comment] 2016-01-09 18:16
Ok, thanks for clarification @bgruening. bioaRchive needs a *lot* of love... really a complete rewrite. Just haven't had time for it.

**Comment by mvdbeek** [comment] 2016-01-11 13:05
One thing that I'm wondering about, how is the interaction with the conda devteam?
We may need documentation updates upstream ...
As an example, I've gone through the [test-drive] (http://conda.pydata.org/docs/test-drive.html) and I think i should be able to install packages, but it fails for me with a pretty useless message:
```
root@vm0148:~# conda install -c https://conda.anaconda.org/bioconda bioconductor-deseq2
Fetching package metadata: ......
Solving package specifications: .....
Error: Could not find some dependencies for bioconductor-deseq2: bioconductor-biobase, bioconductor-biocgenerics >=0.3.2, r 3.2.2*

Did you mean one of these?

    bioconductor-deseq2, bioconductor-dexseq, bioconductor-edger

Did you mean one of these?

    bioconductor-biobase, bioconductor-biovizbase, bioconductor-biocstyle

Did you mean one of these?

    bioconductor-biocgenerics

You can search for this package on anaconda.org with

    anaconda search -t conda r 3.2.2*

 (and similarly for the other packages)
```

Turns out I also needed the r channel. For me this is an issue of upstream documentation and failure handling, .... so will we be able to push doc changes upstream? Any experiences in that direction?

**Comment by bgruening** [comment] 2016-01-15 23:42
Short update from my side: 

We have a work in progress `travis` [branch](https://github.com/galaxyproject/tools-iuc/tree/travis).
This works with conda dependencies that we have added to bioconda and planemo that installs these dependencies and tests the tools. Thanks @jmchilton for fixing planemo and the bioconda community for the fruitful discussions.

There is still some work to do, but I feel ready to show what we have so far to gather a little bit of feedback.
There is a [tool test blacklist](https://github.com/galaxyproject/tools-iuc/blob/travis/.tt_blacklist) and we start with all tools blacklisted. Packages and data_managers are blacklisted as well but in the helper python script as we can not test them properly.

If we want to get a tool under testing we just need to remove it from the blacklist and the correct dependency needs to be in conda.

The idea is to require, at time of merging the branch, a conda dependency for every tool, next to a tool_dependency (until GCC) and every new tools needs to pass these tests.

I would like to propose a new codefest if you all agree and in which the IUC core team and others create conda recipes for our tools and get tools under testing with the aim to empty the blacklist.

Please let me know what you think!

@mvdbeek improving documentation is easy. Just let me know what can be improved and I will do so. Also we are in discussion with bioconda to improve sustainability and I have created an IUC channel that we can use for all stuff that does not fit in bioconda. 

P.S. How to get your tool under testing?
Create a patch like [this](https://github.com/galaxyproject/tools-iuc/commit/a603c8121a7da6dd5c97c36237a3e1c86e906e70) and target it against the `travis` branch.

**Comment by peterjc** [comment] 2017-05-03 14:18
Do we need to review what dependencies are still missing from BioConda? e.g. Looking at Biopython specifically as a dependency:

```
$ grep biopython tools/*/*.xml
tools/jbrowse/macros.xml:      <requirement type="package" version="1.66">biopython</requirement>
tools/kraken_taxonomy_report/kraken_taxonomy_report.xml:        <requirement type="package" version="1.66">biopython</requirement>
tools/ncbi_entrez_eutils/macros.xml:      <requirement type="package" version="1.68">biopython</requirement>
tools/ncbi_entrez_eutils/tool_dependencies.xml:  <package name="biopython" version="1.66">
tools/ncbi_entrez_eutils/tool_dependencies.xml:    <repository name="package_biopython_1_66" owner="biopython"/>
tools/progressivemauve/macros.xml:      <requirement type="package" version="1.65">biopython</requirement>
tools/progressivemauve/tool_dependencies.xml:  <package name="biopython" version="1.65">
tools/progressivemauve/tool_dependencies.xml:    <repository name="package_biopython_1_65" owner="biopython"/>
tools/transtermhp/macros.xml:      <requirement type="package" version="1.65">biopython</requirement>
tools/transtermhp/tool_dependencies.xml:  <package name="biopython" version="1.65">
tools/transtermhp/tool_dependencies.xml:    <repository name="package_biopython_1_65" owner="biopython"/>
```

Since we only have Biopython 1.67 onwards in BioConda, this led me to file https://github.com/bioconda/bioconda-recipes/pull/4590 adding Biopython 1.65 and 1.66 in order to support these tools.

**Comment by bgruening** [comment] 2017-05-03 15:25
@peterjc all these tools https://github.com/galaxyproject/tools-iuc/blob/master/.tt_blacklist are not yet under testing. Means either there is no conda package or we simply have not looked at it yet. If you like to tackle one, simply remove the entry from the blacklist and change something in the wrapper (whitepsace change, upgrading dependency or simply removing the tool_dependencies.xml).

**Comment by peterjc** [comment] 2017-05-03 15:42
As @bgruening explained on https://github.com/bioconda/bioconda-recipes/pull/4590 while these specific examples might not have been able to get the older Biopython conda packages from the bioconda channel, they were available in the default anaconda channel.

Presumably if there are any missing conda dependencies, they will be restricted to those not under automated testing, i.e. https://github.com/galaxyproject/tools-iuc/blob/master/.tt_blacklist

**Comment by peterjc** [comment] 2017-05-09 16:40
I've realised the hard way that the automated testing of tools from this repository does not necessarily cover all the IUC packages, e.g.

* https://toolshed.g2.bx.psu.edu/view/iuc/package_ghostscript_9_07/ (and https://toolshed.g2.bx.psu.edu/view/devteam/package_ghostscript_9_10 too) were missing in BioConda, fixed in https://github.com/bioconda/bioconda-recipes/pull/4650

* https://toolshed.g2.bx.psu.edu/view/iuc/package_gnuplot_4_6 was broken in bioconda, hopefully fixed in https://github.com/bioconda/bioconda-recipes/pull/4655

I will likely stumble over more as I gradually work on my tools with a recent version of planemo which does the dependencies via conda. At some point I will likely switch my own tool continuous integration testing away from ``tool_dependencies.xml`` and manual installation to using conda.

But in general, It would be useful for the community as a whole if all the IUC and devteam packages could be cross-referenced against BioConda (and the other recommended Conda channels) to confirm if a matching version is available.

**Comment by jmchilton** [comment] 2017-05-09 17:26
> It would be useful for the community as a whole if all the IUC and devteam packages could be cross-referenced against BioConda (and the other recommended Conda channels) to confirm if a matching version is available

For the record, ``planemo lint --conda_requirements tool.xml`` extends Planemo's linting to additionally perform this check. More info [here](http://planemo.readthedocs.io/en/latest/writing_advanced.html#specifying-and-using-tool-requirements).

**Comment by bgruening** [comment] 2017-05-09 20:03
@peterjc I had worked on a converter based on your tool_dependencies to bash script, more a tool_dependencies to conda script ... but it is a lot of work. I'm happy to help everyone that is interested in this.

**Comment by peterjc** [comment] 2017-05-09 21:31
Oh, ``planemo lint --conda_requirements ...`` sounds good. That might make it easier to spot missing dependencies early, thanks @jmchilton 👍 

@bgruening - I don't think we'll need a ``tool_dependencies.xml`` to conda script, as mostly things will be in conda now, just not always the older version which some existing Galaxy Tools require (and we want to enable this for reproducibility). Plus it saves tool authors having to do an update just to refresh the dependencies just to get it to run via conda.

But thank you for all your assistance thus far in adding missing versions of BioConda recipes 👍 

I'd still like to run an analysis of all the Tool Shed's iuc/devteam owned packages against the bioconda registry looking for missing recipes or versions. I know the Tool Shed API ought to be helpful here, I've never investigated what the BioConda package repository API is like (assuming there is one).

**Comment by nsoranzo** [comment] 2017-06-08 10:26
Mostly completed, last bits in https://github.com/galaxyproject/tools-iuc/issues/1345.

**Closed by nsoranzo** 2017-06-08 10:26 UTC

**Comment by bgruening** [comment] 2017-06-08 12:20
:tada: :birthday: :gift:
