### ISSUE TITLE
package_perl_5_18 error

### ISSUE THREAD

**Issue by methylome** [galaxyproject/tools-iuc#631] opened 2016-03-02 10:37 UTC
This package has the dependency on package_gnu_coreutils_8_22 although it's not in tool_dependency.xml. 
![package_perl](https://cloud.githubusercontent.com/assets/9466414/13457344/b9722cc8-e035-11e5-8f8e-f9c9d66501c8.png)
Installing it doesn't change the error status of package_perl_5_18.
![package_perl2](https://cloud.githubusercontent.com/assets/9466414/13457942/b7ad5202-e038-11e5-9dde-9a331ae8b8c2.png)
![package_perl3](https://cloud.githubusercontent.com/assets/9466414/13457966/dce84482-e038-11e5-9209-0d51d1de9cb1.png)

**Comment by mvdbeek** [comment] 2016-03-02 10:49
I'm afraid this is a resurgence of a bug that we hoped had been fixed with https://github.com/galaxyproject/galaxy/pull/1193

**Comment by mvdbeek** [comment] 2016-03-02 10:54
Can you try to uninstall both coreutils packages and perl, and then reinstall perl?

**Comment by bgruening** [comment] 2016-03-02 10:59
Also resetting metadata on the TS might help here.

**Comment by mvdbeek** [comment] 2016-03-02 11:08
Hmm, I guess I was in a similar situation, I had the old perl package installed, then I uninstalled perl and installed the new perl, and I only have the correct dependency. So that didn't work before the bugfix, and it still works. I guess a re-install should be enough. Then the question is: How did this happen? Perhaps we need to be more stringent when using "Installl latest revision" ?
@methylome how did you end up in this situation? You updated perl using "install latest revision" in the admin panel? And does it work to uninstall all of coreutils, and then installing just perl?

**Comment by methylome** [comment] 2016-03-02 11:13
While I am trying to reinstall it, I suspect your method because I can see both in the dependency for the installation. So I'm resetting metadata as @bgruening suggested. I had perl installation and ended up this situation after reinstalling sra_toolkit for your update.

**Comment by mvdbeek** [comment] 2016-03-02 11:48
> While I am trying to reinstall it, I suspect your method because I can see both in the dependency for the installation.

What did you do exactly to see this? Which package were you trying to install? perl? sra-tools?
What was the status of the coreutils packages?

**Comment by methylome** [comment] 2016-03-02 11:49
After resetting, only 8_25 is listed on confirmation dependency installation. However, 8_22 is still listed on Installed tool shed repository. On another server which was reset, both are listed on confirmation dependency installation.

**Comment by mvdbeek** [comment] 2016-03-02 11:55
> After resetting, only 8_25 is listed on confirmation dependency installation. However, 8_22 is still listed on Installed tool shed repository

so I guess this is not too bad. If nothing else depends on coreutils_8_22 you can uninstall it.

> On another server which was reset, both are listed on confirmation dependency installation.

I am a bit confused here, did you uninstall everything related to coreutils/perl/and whatever depends on it? Did you do the same things to both servers? They are both running a recent commit of 16.01 ?

**Comment by methylome** [comment] 2016-03-02 11:57
I tried to reinstall perl and saw the attached one. Only package_gnu_coreutils_8_25 was installed successfully.
![package_perl4](https://cloud.githubusercontent.com/assets/9466414/13459703/85cdbb36-e043-11e5-93c0-1700496795ab.png)
While the status of perl is installed, the status of package_perl_5_18 is Installed, missing repository dependencies because the status of package_gnu_coreutils_8_22 is uninstalled, missing tool dependencies.

**Comment by methylome** [comment] 2016-03-02 12:00
> I am a bit confused here, did you uninstall everything related to coreutils/perl/and whatever depends on it? Did you do the same things to both servers? They are both running a recent commit of 16.01 ?

Yes.

**Comment by mvdbeek** [comment] 2016-03-02 12:01
> Yes.

Well, then what is going on in the screenshot?

**Comment by methylome** [comment] 2016-03-02 12:02
Screenshot is the same as before.

**Comment by methylome** [comment] 2016-03-02 12:07
I think resetting and reinstallation don't work. Actually, one server was cloned yesterday and then tools were installed. This is different from another server where sra_toolkit was updated.

**Comment by mvdbeek** [comment] 2016-03-02 12:10
okay, so I guess there are still situations where https://github.com/galaxyproject/galaxy/pull/1193 can occur. I'm trying to reproduce this, but it's tough, since you can't install an old revision of a package.

**Comment by mvdbeek** [comment] 2016-03-02 12:13
Just to be sure, you do have this line in `<galaxy_dir>/lib/tool_shed/util/shed_util_common.py` ?
```def clean_dependency_relationships(trans, metadata_dict, tool_shed_repository, tool_shed_url):```

**Comment by methylome** [comment] 2016-03-02 12:14
I'm not sure what do you mean and do think you can reproduce it because I cloned galaxy yesterday and installed the latest tools. It ended up the same problem.

**Comment by mvdbeek** [comment] 2016-03-02 12:15
Do it today and it will work, since perl has switched it's coreutils dependency from 8_22 to 8_25 yesterday.

**Comment by methylome** [comment] 2016-03-02 12:15
Yes I do.
def clean_dependency_relationships(trans, metadata_dict, tool_shed_repository, tool_shed_url):
    """
    Repositories of type tool_dependency_definition allow for defining a
    package dependency at some point in the change log and then removing the
    dependency later in the change log.  This function keeps the dependency
    relationships on the Galaxy side current by deleting database records
    that defined the now-broken relationships.
    """
    for rrda in tool_shed_repository.required_repositories:
        rd = rrda.repository_dependency
        r = rd.repository
        if can_eliminate_repository_dependency(metadata_dict, tool_shed_url, r.name, r.owner):
            trans.install_model.context.delete(rrda)
            trans.install_model.context.flush()
    for td in tool_shed_repository.tool_dependencies:
        if can_eliminate_tool_dependency(metadata_dict, td.name, td.type, td.version):
            trans.install_model.context.delete(td)
            trans.install_model.context.flush()

**Comment by mvdbeek** [comment] 2016-03-02 12:16
yes, this bug has a long history. it started here:
https://github.com/galaxyproject/galaxy/issues/667

**Comment by mvdbeek** [comment] 2016-03-02 14:20
@methylome can you try this patch?
https://github.com/galaxyproject/galaxy/compare/release_16.01...mvdbeek:fix_ts_install_old_tool_deps.diff

This way it should be sufficient to uninstall and re-install perl. I finally was able to reproduce the behaviour, but since it seems to work now it's difficult to confirm.

**Comment by methylome** [comment] 2016-03-02 15:27
Awesome, it works.

**Comment by mvdbeek** [comment] 2016-03-05 16:24
I guess we can close it then.

**Closed by mvdbeek** 2016-03-05 16:24 UTC
