### ISSUE TITLE
picard_SamToFastq losing name of initial dataset

### ISSUE THREAD

**Issue by NairaNaouar** [galaxyproject/tools-iuc#3236] opened 2020-10-07 14:00 UTC
Hi,

I have run the Sam to fastq tool on a big collection of 200 bam files to obtain fastq interleaved files from the bam.

I have a problem with my outputs. The tool provides me as output : a collection of 200 text files  with the initial names where in each text file is written "BAM" and 200 other outputs all named : *SamToFastq run (INTERLEAVED)* which of course were not generated in the same order as the initial collection.
The only way to get the original BAM file name is to go to the "Info" section of the generated fastq file.
Is there a way to access that information to rename the dataset in the history?
Wouldn't it be better to change the output in this tool?

Thanks a lor,
Naïra

**Comment by NairaNaouar** [comment] 2020-10-09 13:42
Hello

Coming back to my previous answer it seems that it is a real bug from the tool.

Naïra

**Comment by bernt-matthias** [comment] 2020-10-13 21:01
Do you have a public history that you could share? 

As a "workaround": any chance that you give the tool `Samtools fastx` a chance?

**Comment by NairaNaouar** [comment] 2020-10-14 08:07
Hi @bernt-matthias 
Yes sure you can access the result of the samtofastq tool with default options [here](https://artbio.snv.jussieu.fr/u/naira/h/samtofastq-default-options )
and with the "interleaved option" [here](https://artbio.snv.jussieu.fr/u/naira/h/samtofastq-interleaved)

I will also look ant the samtools fastx tool.
Naïra

**Comment by bernt-matthias** [comment] 2020-10-14 09:38
Is your data really paired end? If not choosing one of the PE options is wrong. 

Independent of this, the problem seems to be limited to artbio.snv.jussieu.fr. I tried on usegalaxy.eu and the tools works as expected. Please contact the admins of this galaxy instance and report the problem. 

I think the root of the problem is the Collection 'SamToFastq run' which should not be created at all...

I'm going to close the issue here. Reopen if needed

**Closed by bernt-matthias** 2020-10-14 09:38 UTC

**Comment by NairaNaouar** [comment] 2020-10-15 08:06
Hi @bernt-matthias 

In fact, we have the same issues on our server and usegalaxy.eu with the tool Samtofastq version 2.18.2.1, versio that I used.
I did not realised that the SamtoFastq was upgraded to 2.18.2.2 cause all other tools were 2.18.2.1 ;)

So upgrading to this new version will correct the bug I guess ;)

However, thanks a lot for having a look at this.

Naïra
