### ISSUE TITLE
Unify testing of Galaxy tools across repositories

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#991] opened 2016-10-11 07:55 UTC
The IUC is taking a leading role in developing best-practices for Galaxy tool development and I think we do this as well for Tool testing. 

Maybe we should have a new repository similar to https://github.com/bgruening/galaxy-flavor-testing so that all project, like GalaxyP, galaxytools, W4M etc. can share one set of tests that are constantly updated and maintained.

ping @galaxyproject/iuc

**Comment by mvdbeek** [comment] 2016-10-11 07:58
Yes ... I am just copying the iuc tests for https://github.com/artbio/tools-artbio, and I think @peterjc is doing this similarly for his tools. That would definitely be good.
P
erhaps we should even have a docker container for the tests, since I think that could speed up testing slightly and make it easier to test locally without travis.

**Comment by peterjc** [comment] 2016-10-11 09:23
My tests predated the IUC setup, but I have been updating them to use planemo more fully in line with the IUC setup. One major difference is currently I just test all the tools in each repository (still manageable run time).

Separately ``planemo travis_init`` will setup a minimal TravisCI setup, see eg https://github.com/galaxyproject/planemo/blob/master/scripts/travis_test.sh - but that is different again. I'd like to see work on that as the priority (even if internally planemo just uses the new common repository @bgruening is suggesting?).

**Comment by bgruening** [comment] 2016-10-11 09:49
@mvdbeek there was work done by @jmchilton to use an `engine` to test tools, e.g. `--docker_galaxy_image`. This could one option we can offer. We have some tools that do not work with the local-job runner and needs some advance setup.

**Comment by bgruening** [comment] 2016-10-11 09:50
To make it clear, we can offer a variety of Make targets to fulfill @peterjc and other needs, but it would be nice to collect all of them somewhere.

**Comment by gregvonkuster** [comment] 2016-10-11 14:01
I'm using the new testing approach created by @bgruening here: https://github.com/gregvonkuster/docker-galaxy-csg/blob/master/.travis.yml, but I am a bit unclear how the back-end is working.

My CSG tools require OpenGl, so I have defined the following in my Docker file Here: https://github.com/gregvonkuster/docker-galaxy-csg/blob/master/Dockerfile
```
RUN apt-get -qq update && apt-get install --no-install-recommends -y libgl1-mesa-dev libgl1-mesa-dri libglu1-mesa x11-xserver-utils x11vnc xinit xserver-xorg-video-dummy xserver-xorg-input-void
```
Do I need these same dependencies defined in my .travis.yml file as I've defined them:
```
before_install:
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  - sudo apt-get install --no-install-recommends -y libgl1-mesa-dev libgl1-mesa-dri x11-xserver-utils x11vnc xinit xserver-xorg-video-dummy xserver-xorg-input-void
  - docker --version
  - docker info
  - travis_wait 45 make docker_build
  - make docker_run
  - sleep 30
```
Or will tests pass without specifying these additional dependencies so that I can use @bgruening simpler approach:
```
before_install:
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  - make docker_install
  - travis_wait 45 make docker_build
  - make docker_run
  - sleep 30
```

**Comment by bgruening** [comment] 2016-10-11 23:15
@gregvonkuster I guess OpenGL is not a dependency of the conda package? Than you need your first approach to make sure that your travis installation has all dependencies.

You could still use `- make docker_install` in your first example.

**Comment by gregvonkuster** [comment] 2016-10-12 11:47
@bgruening ok, thanks - this clears things up.

**Comment by abretaud** [comment] 2019-10-29 07:14
Duplicate of #1401

**Closed by abretaud** 2019-10-29 07:14 UTC
Labels: help wanted, planning
