### ISSUE TITLE
Bug: snpEff 5.2+galaxy0 will not execute with a snpEff_build_gb 5.2+galaxy0 database

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#6571] opened 2024-11-18 18:43 UTC
toolshed.g2.bx.psu.edu/repos/iuc/snpeff/snpEff/5.2+galaxy0
toolshed.g2.bx.psu.edu/repos/iuc/snpeff/snpEff_build_gb/5.2+galaxy0

Recent changes to turning off the db check seems to have problems. The warning box in blue goes away then pops back up and prevents the tool from submitting. Any server, several different test and real data runs. Has anyone been able to get this to work after the late Oct updates?

Workaround for end users:
1. Create your snpeffdb with SnpEff build 4.3+T.galaxy6 first
2. Then use SnpEff eff 4.3+T.galaxy2
3. Note that you might need to submit the job a few times to get it to go through

Reported at https://help.galaxyproject.org/t/snpeff-database-compatibility/13923/5

One of the test histories: https://usegalaxy.eu/u/jenj/h/test-snpeff-build

Screenshots: notice how the message will repeat and populate again if you click on the submit button a few times with v 5.2. Doing the repeat submission will allow a 4.3 job to eventually submit and run. 

![Screen Shot 2024-11-18 at 10 28 39 AM](https://github.com/user-attachments/assets/4d46cf7d-925b-49fc-b65f-b763f4a26bec)

![Screen Shot 2024-11-18 at 10 39 21 AM](https://github.com/user-attachments/assets/c05e8c4a-7f3f-42dd-90c5-a8d30f33f814)

**Comment by wm75** [comment] 2024-11-19 11:55
works now with the new version installed on .eu

**Comment by wm75** [comment] 2024-11-19 11:59
The repeated required submissions problem you're describing is a different issue I think, which I cannot reproduce at least for the moment.

**Comment by wm75** [comment] 2024-11-21 11:08
Closing as fixed according to https://help.galaxyproject.org/t/snpeff-database-compatibility/13923/7

**Closed by wm75** 2024-11-21 11:08 UTC
