### ISSUE TITLE
MACS2: Incorrect BED format

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/tools-iuc#96] opened 2015-04-07 13:29 UTC
The XLS to BED conversion in "callpeak" is incorrect as it places the name column at the very end instead of in column 4.
See https://github.com/galaxyproject/tools-iuc/blob/master/tools/macs2/macs2_callpeak.xml#L83

**Comment by blankenberg** [comment] 2015-04-08 14:12
Confirmed. Also the output file is more generic interval than bed (lots of non-bed standard columns here).

**Comment by bgruening** [comment] 2015-08-02 20:12
@scholtalbers do you mind to create a PR for this?

**Comment by lparsons** [comment] 2016-01-26 16:58
I decided to change the output file format to tabular since that is what MACS outputs anyway. There are other outputs (narrowpeaks, broadpeaks, etc.) that are in BED format, but the peaks.xls file is it's own tabular format (see https://github.com/taoliu/MACS#output-files). Also, updated to the latest point release.

**Comment by nsoranzo** [comment] 2016-01-27 20:26
Should be fixed by #570.

**Closed by nsoranzo** 2016-01-27 20:26 UTC
Labels: bug, help wanted, missing tests
