### ISSUE TITLE
JBrowse 0.5.3.2 Execute error

### ISSUE THREAD

**Issue by aifennng** [galaxyproject/tools-iuc#1559] opened 2017-11-07 03:36 UTC
Galaxy 17.05 / 17.09

Dataset Error
An error occured while running the tool toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/jbrowse/0.5.3.2.

Tool execution generated the following messages:

```
Fatal error: Exit code 1 ()
find: In ‘-exec ... {} +’ the ‘{}’ must appear by itself, but you specified ‘'{}'’
Traceback (most recent call last):
  File "/share/apps/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b5c5470d7c09/jbrowse/jbrowse.py", line 702, in 
    gencode=root.find('metadata/gencode').text
  File "/share/apps/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b5c5470d7c09/jbrowse/jbrowse.py", line 307, in __init__
    self.clone_jbrowse(self.jbrowse, self.outdir)
  File "/share/apps/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b5c5470d7c09/jbrowse/jbrowse.py", line 682, in clone_jbrowse
    subprocess.check_call(cmd)
  File "/share/apps/galaxy/galaxy_17.09/database/dependencies/_conda/envs/mulled-v1-4f60687598c40f0675c7de956d89c6ebcb6abb8d1faef576907dbea7330e0778/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['find', '/share/apps/galaxy/galaxy_17.09/database/jobs_directory/000/77/dataset_349_files', '-type', 'l', '-xtype', 'l', '-exec', 'rm', "'{}'", '+']' returned non-zero exit status 1
```

**Comment by bgruening** [comment] 2017-11-07 03:49
@aifennng can you please try that this command:

`find /share/apps/galaxy/galaxy_17.09/database/jobs_directory/000/77/dataset_349_files -type l -xtype l -exec rm '{}' +`

works in principle on your machine? The file can be replaced by another file.

**Comment by aifennng** [comment] 2017-11-07 03:58
@bgruening Thank u for ur help. But there is no folder  

> /share/apps/galaxy/galaxy_17.09/database/jobs_directory/000/77

only the folder

>  /share/apps/galaxy/galaxy_17.09/database/jobs_directory/000/58

with the command, the machine returns

`find: ‘/share/apps/galaxy/galaxy_17.09/database/jobs_directory/000/77/dataset_349_files’: no such file or directory`

**Comment by bgruening** [comment] 2017-11-07 04:01
Use an arbitrary other file. Just want to check if this command works in theory.

**Comment by aifennng** [comment] 2017-11-07 04:19
@bgruening OK, I see. I think the command work.

`find /share/apps/galaxy/galaxy_17.09/database/jobs_directory/000/58/metadata_temp_file_ZVHX7V -type l -xtype l -exec rm '{}' + `

with no read output

**Comment by abretaud** [comment] 2017-11-15 17:17
I can't reproduce this, it's strange... Which shell are you using ? Which version of it and of find?

**Comment by aifennng** [comment] 2017-11-16 01:25
@abretaud 
the shell is bash, Version:
GNU bash， version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
find version:
find (GNU findutils) 4.5.11
OS:
CentOS 7 X64
Is there anything else need to attention when configure the jbrowse？Thank you!

**Comment by aifennng** [comment] 2017-11-16 01:33
@abretaud 
After update to jbrowse 17(2017-11-15), the error is change:
`Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/share/apps/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/ff11d442feed/jbrowse/jbrowse.py", line 848, in 
    for x in root.findall('metadata/genomes/genome')
KeyError: 'path'`

**Comment by abretaud** [comment] 2017-11-16 10:07
For the find problem, I still can't reproduce in a centos docker... I'll continue investigating

The python error is unrelated, it's a bug :/ I'll have a fix for it soon, in the meantime using a genome fasta fiel from your history should work

**Comment by abretaud** [comment] 2017-11-16 11:05
I just realized that the newest jbrowse tool doesn't use this -exec option anymore, see https://github.com/galaxyproject/tools-iuc/commit/886ac53cdda1ea8ee57117eff7e4b5fdc24ad82e

So can you wait for #1580 to be merged and then test and hopefully confirm that the problem is fixed?
Thanks!

**Comment by aifennng** [comment] 2017-11-16 13:08
@abretaud 
Thank you for your help! It works when I import a fasta file to the history.
But I'm new to use the Jbrowse.
How can I view the result of Jbrowse? I press "view data", and the galaxy show a blank page with some words:
```
JBrowse &process.versions&process.versions.electron
JBrowseDefaultMainPage
```
And I press "show details", I notice that there is an error under "Job Information":
`
Tool Version: | python: can't open file 'jbrowse.py': [Errno 2] No such file or directory`

Is there anything wrong?

**Comment by abretaud** [comment] 2017-11-16 13:36
To display the result, you will need to either set sanitize_all_html=False in galaxy.ini, or whitelist jbrowse in Manage Display Whitelist in the Galaxy Admin.

The "No such file or directory" should not have any impact on the generated jbrowse, the error should go away with https://github.com/galaxyproject/tools-iuc/pull/1580/commits/ee1ddac197e3ce6f6bbabf575170acf44ff0ad17

**Comment by aifennng** [comment] 2017-11-16 14:10
emm...I forgot that! OK, now it works! Thanks you once again! @abretaud 
And waiting for the fix

**Comment by abretaud** [comment] 2017-11-16 15:09
Cool, have fun!
thanks

**Closed by abretaud** 2017-11-16 15:09 UTC
