### ISSUE TITLE
HOMER should be a Galaxy tool provided by the IUC

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/tools-iuc#1696] opened 2018-01-30 18:34 UTC
[HOMER](http://homer.ucsd.edu/homer/) is a tool widely used for ChIP-seq (and other NGS) data analysis. 

There are two HOMER tools on Galaxy: 
- [`homer` by keyvin](https://toolshed.g2.bx.psu.edu/repository?repository_id=aaa8f7315ce6dac2&changeset_revision=74c1fc7bb164) which, if I'm reading correctly, hasn't been updated since 2012, despite HOMER's relatively frequent enhancements (most recent release was a week ago, of v4.9).
- [`homer_47` by chseward](https://toolshed.g2.bx.psu.edu/repository?repository_id=d64d9630d122a665&changeset_revision=9764a14c8e3a) which is meant to implement homer version 4.7 (relatively recent) but fails to install. 

Galaxy would benefit a great deal from a reference implementation of a HOMER galaxy tool. 

cc @bwassie, @bgruening

**Comment by bgruening** [comment] 2018-01-30 20:30
@zfrenchee A start is here: https://github.com/bgruening/galaxytools/tree/master/tools/homer
I welcome you to help :)

**Comment by abretaud** [comment] 2019-10-29 07:18
duplicate of #1892

**Closed by abretaud** 2019-10-29 07:18 UTC
