### ISSUE TITLE
 tetoolkit_tetranscripts

### ISSUE THREAD

**Issue by sanatbhadsavle** [galaxyproject/tools-iuc#4144] opened 2021-11-05 15:24 UTC

**Comment by bernt-matthias** [comment] 2021-11-30 21:15
duplicate of https://github.com/galaxyproject/tools-iuc/issues/4143 ?

**Closed by bernt-matthias** 2021-11-30 21:15 UTC

**Comment by bernt-matthias** [comment] 2021-11-30 21:17
https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/tetoolkit_tetranscripts/tetoolkit_tetranscripts/2.2.1+galaxy0
