### ISSUE TITLE
Numpy 1.7 dies due to missing libf77blas.so.3

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#104] opened 2015-04-10 21:06 UTC
When attempting to use MACS2 (which depends on numpy 1.7) I get the following error:

    ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

Atlas seems to be installed just fine, but it doesn't seem like that env.sh is sourced except during numpy installation. Not sure if that's the issue, but seems like it might be.

**Comment by erasche** [comment] 2015-04-15 13:38
We now provide numpy with atlas compiled in, which version of MACS2/numpy are you using? We had one other person report a very similar issue but I'd have to dig through IRC logs.

**Comment by lparsons** [comment] 2015-04-15 18:00
Using the latest MACS2 (`859c982b1f7f`) and letting Galaxy handle dependencies, which installs:

    package_r_3_0_1         iuc	c5ff6dd33c79	Installed
    package_gnu_awk_4_1_0   iuc	52a8268bb49f	Installed
    package_atlas_3_10      iuc	37ff27ea37ed	Installed
    package_numpy_1_7       iuc	c7ae57300a77	Installed
    package_scipy_0_12      iuc	20d1dd0220d7	Installed
    macs2                   iuc	859c982b1f7f	Installed
    package_macs2_2_1_0     iuc	4d7ef54c3fa4	Installed

**Comment by erasche** [comment] 2015-04-15 18:12
Huh, that's odd. According to the diff
https://toolshed.g2.bx.psu.edu/repository/view_changeset?ctx_str=859c982b1f7f&id=e984c9f63184b207
it should install package_numpy_1_7 at 692ae723f63e which is two commits
behind yours. Wonder why it's ignoring specific changeset revision
information.

Anyway, back to your issue...that LOOKS like it's suppose to work. I'll see
if I can reproduce it later and debug. Thanks for the information lance!

ons. 15. apr. 2015 kl. 13.00 skrev Lance Parsons <notifications@github.com>:

**Comment by lparsons** [comment] 2015-04-15 18:29
I've definitely had issues with package_* dependencies changing revisions.
Could be there was an earlier one installed?  I often end up with two
records in Galaxy for different revisions of the sample package_*
dependency.  I'm never really sure how to resolve it, any tips on how to
"clean up" the list of installed revisions would be most welcome.

Lance

On Wed, Apr 15, 2015 at 2:12 PM, Eric Rasche <notifications@github.com>
wrote:

> Huh, that's odd. According to the diff
>
> https://toolshed.g2.bx.psu.edu/repository/view_changeset?ctx_str=859c982b1f7f&id=e984c9f63184b207
> it should install package_numpy_1_7 at 692ae723f63e which is two commits
> behind yours. Wonder why it's ignoring specific changeset revision
> information.
>
> Anyway, back to your issue...that LOOKS like it's suppose to work. I'll see
> if I can reproduce it later and debug. Thanks for the information lance!
>
> ons. 15. apr. 2015 kl. 13.00 skrev Lance Parsons <notifications@github.com
> >:
>
> > Using the latest MACS2 (859c982b1f7f) and letting Galaxy handle
> > dependencies, which installs:
> >
> > package_r_3_0_1 iuc c5ff6dd33c79 Installed
> > package_gnu_awk_4_1_0 iuc 52a8268bb49f Installed
> > package_atlas_3_10 iuc 37ff27ea37ed Installed
> > package_numpy_1_7 iuc c7ae57300a77 Installed
> > package_scipy_0_12 iuc 20d1dd0220d7 Installed
> > macs2 iuc 859c982b1f7f Installed
> > package_macs2_2_1_0 iuc 4d7ef54c3fa4 Installed
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/galaxyproject/tools-iuc/issues/104#issuecomment-93504514
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/issues/104#issuecomment-93511454>
> .
>



-- 
- Lance Parsons

**Comment by bgruening** [comment] 2015-04-15 18:34
Do you see "white ghosts"? Repositories that are not installed, just white and doubled?
If so you can purge such repositories.

**Comment by bgruening** [comment] 2015-04-15 18:35
Do you see "white ghosts"? Repositories that are not installed, just white and doubled?
If so you can purge such repositories.

**Comment by lparsons** [comment] 2015-04-15 18:38
That might happen, but more often I see two "Installed".  I believe this happens when "updating to latest revision", though it's been hard to keep track. I'm guessing this might be an issue here, but not sure.  I will try to do some tests and post results here, and perhaps a trello ticket if I can collect enough useful info on the issue.

**Comment by bgruening** [comment] 2015-04-15 18:41
@lparsons thanks this would help a lot!

**Comment by lparsons** [comment] 2015-04-15 19:04
Uninstalled macs2 and all copies of each dependency listed above. Restarted Galaxy server, browsed toolshed for macs2, clicked on install and got these dependencies listed (seems like they are old revisions?)
![image](https://cloud.githubusercontent.com/assets/645128/7167128/a5ecd980-e380-11e4-9c25-60817ac5edd1.png)

**Comment by bgruening** [comment] 2015-04-15 19:25
@lparsons how old is this Galaxy instance? This looks really old! I have reset the metadata can you please try again?

**Comment by lparsons** [comment] 2015-04-15 19:41
The instance has been running since about 2011, however, the software is at 'latest_2014.10.06'.

I have reset metadata quite a few times, I did it again.  Claimed sucessful on all but 2 repositories (though I couldn't find which ones in the paster.log).  Lots of lines like:

    galaxy.tools.data DEBUG 2015-04-15 15:37:15,169 Attempted to add fields (['LowMQ', 'LowMQ', 'LowMQ', 'UnifiedGenotyper,VariantAnnotator,VariantRecalibrator']) to data table 'gatk_annotations', but this entry already exists and allow_duplicates is False.

One thing I noticed is that there are two columns in the db, `changeset_revision` (which both shows the same value) and `installed_changeset_revision` which is different. See:

    galaxy=> select id,name,tool_shed,owner,changeset_revision,installed_changeset_revision,status from tool_shed_repository where name='package_r_3_0_1' and owner='iuc' and tool_shed='toolshed.g2.bx.psu.edu';
     id |      name       |       tool_shed        | owner | changeset_revision | installed_changeset_revision |   status
    ----+-----------------+------------------------+-------+--------------------+------------------------------+-------------
     27 | package_r_3_0_1 | toolshed.g2.bx.psu.edu | iuc   | c5ff6dd33c79       | 7473992d1f38                 | Uninstalled
     91 | package_r_3_0_1 | toolshed.g2.bx.psu.edu | iuc   | c5ff6dd33c79       | c5ff6dd33c79                 | Uninstalled

**Comment by bgruening** [comment] 2015-04-15 19:44
Time to call for @davebx!

**Comment by martenson** [comment] 2015-04-23 16:58
@lparsons The `installed_changeset_revision` is the revision of the repo in the time of installation and should not be changing I think. We had similar issues on Test with other tools and @natefoo resolved them by manually correcting the changesets in shed_tool_conf.xml (https://github.com/galaxyproject/usegalaxy-playbook/commit/2892cd70f4666c0b1eb905b6a74813f296b9f039)
@blankenberg and @davebx and @jmchilton might have more insights

We are aware these are multiple issues/bugs that make Galaxy admin's life difficult but tracking them down to the source we were not able yet. These situations happen the most in the 'old' (in manner of when the database was started to be used) Galaxies and I did not succeed in reproducing it locally. However Test and Main are hitting them occasionally too :/

**Comment by lparsons** [comment] 2015-04-23 17:26
@martenson Thanks for info, it helps to know it's not just me.

Any advice on what values to put in the shed_tool_conf.xml file?

As a general comment, it would be really nice to move things like shed_tool_conf.xml into the database entirely. I feel like having configuration info in both places is what leads to a lot of these issues. Has there been any work toward that?

**Comment by natefoo** [comment] 2015-04-29 15:46
@lparsons Completely agree about the duplication of information and the problems with them becoming out of sync. Unfortunately there hasn't been any work to this end. If there isn't already a Trello card to track it, one should be created.

If I recall correctly, I had to change `installed_changeset_revision` to the same changeset ID as the version originally installed on disk - it should match the name of the changeset hash directory into which the package is installed. e.g. if you expand some of the in-between lines in the changeset @martenson linked, you can see this:

```xml
<tool file="toolshed.g2.bx.psu.edu/repos/devteam/cluster/9fcc3a1c3d26/cluster/cluster.xml" guid="toolshed.g2.bx.psu.edu/repos/devteam/cluster/gops_cluster_1/1.0.0">
  ...
    <installed_changeset_revision>9fcc3a1c3d26</installed_changeset_revision>
  ...
```

**Comment by lparsons** [comment] 2015-06-23 21:14
After lots of uninstalling, restarting, and finally, a whole lot of setting status to "New" and using "Purge" I was able to get MACS2 working. I'm concerned that other things are broken now, but at least there was some progress. Currently stuck on getting package_htseq_0_6 to install (fails for find the matplotlib install and complains that numpy is not installed).

**Comment by lparsons** [comment] 2015-07-24 19:11
I'm still having issues with `numpy` and `libf77blas.so`, at least with `package_htseq_0_6`. It seems like the `env.sh` file for atlas is never sourced. I'm not sure when/where that is supposed to happen, but this is the command that gets generated:
```
PACKAGE_BASE=/data/local/galaxy/galaxy-prod/tool-dependencies/htseq/0.6.1/lparsons/htseq_count/3b3601a2a7c7; export PACKAGE_BASE; . /data/local/galaxy/galaxy-prod/tool-dependencies/htseq/0.6.1/lparsons/
htseq_count/3b3601a2a7c7/env.sh; PACKAGE_BASE=/data/local/galaxy/galaxy-prod/tool-dependencies/samtools/0.1.19/lparsons/htseq_count/3b3601a2a7c7; export PACKAGE_BASE; . /data/local/galaxy/galaxy-prod/tool-dependencies/samtools/0.1.19/lparsons/htseq_count/3b3601a2a7c7/env.
sh; PACKAGE_BASE=/data/local/galaxy/galaxy-prod/tool-dependencies/pysam/0.7.7/lparsons/htseq_count/3b3601a2a7c7; export PACKAGE_BASE; . /data/local/galaxy/galaxy-prod/tool-dependencies/pysam/0.7.7/lparsons/htseq_count/3b3601a2a7c7/env.sh; htseq-count -h | grep version | s
ed 's/^\(.*\)*\(version .*\)\./\2/' > /data/local/galaxy/galaxy-prod/database/tmp/GALAXY_VERSION_STRING_71248 2>&1; htseq-count ...
```
None of those `env.sh` files actually attempt to source the atlas `env.sh` file. Is something wrong in my installs or does this work for other people?  If so, where should the atlas `env.sh` be sourced?

**Comment by lparsons** [comment] 2015-07-24 19:34
OK, sorry for all the spam. I've tracked down the issue to problems during installation. When I install `package_numpy_1_7` the env.sh file is rather borked (and it's borked in a slightly different way each install). The paths are incomplete and partially duplicated. I'm reluctant to file a bug until I can track this down a bit better, but can someone point me to relevant code so I can try and trace what is going on here?

**Comment by gregvonkuster** [comment] 2015-07-24 19:53
Hi Lance,

I believe this behavior may have been fixed in this pull request:

https://github.com/galaxyproject/galaxy/pull/403 <https://github.com/galaxyproject/galaxy/pull/403>

I think this fix is still in the dev branch though.  What version are you running?

Greg

**Comment by bgruening** [comment] 2015-07-24 19:56
@gregvonkuster is back!
Discussion moved to: https://github.com/galaxyproject/tools-iuc/issues/221#issuecomment-124686365

**Comment by bgruening** [comment] 2015-07-26 16:59
@lparsons is this fixed now?

**Comment by lparsons** [comment] 2015-07-27 17:54
I believe this is fixed by galaxyproject/galaxy#403, as mentioned in galaxyproject/tools-iuc#221

**Closed** 2015-07-27 17:56 UTC
Labels: bug

**Comment by lparsons** [comment] 2015-07-28 14:06
@bgruening @gregvonkuster Unfortunately, this does not appear to be fixed. I'm going to have to revert to the older versions of `htseq-count` that do not depend on the broken `package_htseq_0_6` and `package_numpy_1_7` packages for the time being.

**Comment by bgruening** [comment] 2015-07-28 14:14
@lparsons do you still see the $ENV vars unfolded?

**Comment by lparsons** [comment] 2015-07-28 14:25
The $ENV vars seems to be fixed. However, when package_htseq_0_6 requires numpy, the LD_LIBRARY_PATH is never set, which means that during execution, numpy is unable to find the atlas library.

I could think of a few of ways to fix this. The first suggested by @gregvonkuster involves exporting an environment var from ATLAS and using that for any package that requires numpy. While this would work, it seems very tedious for the tool writers. It has the benefit, however, of not requiring any changes to Galaxy and thus could be implemented quickly.

Another option would be to source each env.sh file for any required dependencies. To me, as a tool developer, this is what I would have expected Galaxy to do. If I say I require numpy, I get a working numpy with no further effort.

Finally, (and this could be done in conjunction with the above options), would be to use configure flags to specify library and include paths during installations so that LD_LIBRARY_PATH does not need to be set. For example: 
```
CFLAGS="-I$HOME/include" CPPFLAGS="-I$HOME/include" LDFLAGS="-L$HOME/lib -Wl,-rpath,$HOME/lib" ./configure --prefix=$HOME
```
The downside here is that if a dependency gets changed (and moved somehow, etc) the downstream packages would need to be rebuilt. I'm in favor of sourcing the env.sh for each dependency. Thoughts?

**Comment by gregvonkuster** [comment] 2015-07-28 14:40
It's unclear why LD_LIBRARY_PATH is not properly set because the package_numpy_1_7 recipe defines an env.sh file that should be setting LD_LIBRARY_PATH with the following tags:

<environment_variable action="prepend_to" name="LD_LIBRARY_PATH">$ENV[ATLAS_LIB_DIR]</environment_variable>
<environment_variable action="prepend_to" name="LD_LIBRARY_PATH">$ENV[ATLAS_LIB_DIR]/atlas</environment_variable>

The paths should be available in $ENV due to the following tag in the package_atlas_3_10 recipe:

<environment_variable action="set_to" name="ATLAS_LIB_DIR">$INSTALL_DIR/lib</environment_variable>

What does your env.sh file include after installing package_atlas_3_10 and what does your env.sh file include after installing package_numpy_1_7?

FWIW, I'm all for sourcing the env.sh file for each and every required dependency.  I thought @bgruening had committed a small change (a few weeks ago) that now does this.  Am I remembering incorrectly, or perhaps did that change not result in what we were hoping for?  I cannot easily find the commit at this point.

**Comment by lparsons** [comment] 2015-07-28 14:52
Perhaps I'm missing something, but I don't see anywhere that the package_numpy_1_7 env.sh is sourced when running the htseq-count tool. That tool has a dependency on samtools, pysam, and htseq: https://github.com/lparsons/galaxy_tools/blob/master/tools/htseq_count/tool_dependencies.xml

The env.sh files look correct to me once I applied your patch and reinstalled everything.

The `package_atlas_3_10` `env.sh` is:
```
ATLAS_LIB_DIR=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib; export ATLAS_LIB_DIR
ATLAS_INCLUDE_DIR=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/include; export ATLAS_INCLUDE_DIR
ATLAS_BLAS_LIB_DIR=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib/atlas; export ATLAS_BLAS_LIB_DIR
ATLAS_LAPACK_LIB_DIR=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib/atlas; export ATLAS_LAPACK_LIB_DIR
ATLAS_ROOT_PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119; export ATLAS_ROOT_PATH
LD_LIBRARY_PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
LD_LIBRARY_PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib/atlas:$LD_LIBRARY_PATH; export LD_LIBRARY_PATHgalaxy@rebec:/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119
```


The `package_numpy_1_7` `env.sh` is:
```
PYTHONPATH=/data/local/galaxy/galaxy-prod/tool-dependencies/numpy/1.7.1/iuc/package_numpy_1_7/300877695495/lib/python:$PYTHONPATH; export PYTHONPATH
PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/numpy/1.7.1/iuc/package_numpy_1_7/300877695495/bin:$PATH; export PATH
LD_LIBRARY_PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
LD_LIBRARY_PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/0538fd672119/lib/atlas:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
PYTHONPATH_NUMPY=/data/local/galaxy/galaxy-prod/tool-dependencies/numpy/1.7.1/iuc/package_numpy_1_7/300877695495/lib/python; export PYTHONPATH_NUMPY
PATH_NUMPY=/data/local/galaxy/galaxy-prod/tool-dependencies/numpy/1.7.1/iuc/package_numpy_1_7/300877695495/bin; export PATH_NUMPY
```

The `package_htseq_0_6` `env.sh` is:
```
PYTHONPATH=/data/local/galaxy/galaxy-prod/tool-dependencies/htseq/0.6.1/iuc/package_htseq_0_6/fbb72996807d/lib/python:$PYTHONPATH; export PYTHONPATH
PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/htseq/0.6.1/iuc/package_htseq_0_6/fbb72996807d/bin:$PATH; export PATH
PYTHONPATH=/data/local/galaxy/galaxy-prod/tool-dependencies/numpy/1.7.1/iuc/package_numpy_1_7/300877695495/lib/python:$PYTHONPATH; export PYTHONPATH
PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/numpy/1.7.1/iuc/package_numpy_1_7/300877695495/bin:$PATH; export PATH
PYTHONPATH=/data/local/galaxy/galaxy-prod/tool-dependencies/matplotlib/1.2.1/iuc/package_matplotlib_1_2/50b86df1f968/lib/python:$PYTHONPATH; export PYTHONPATH
HTSEQ_ROOT_PATH=/data/local/galaxy/galaxy-prod/tool-dependencies/htseq/0.6.1/iuc/package_htseq_0_6/fbb72996807d; export HTSEQ_ROOT_PATHgalaxy@rebec:/data/local/galaxy/galaxy-prod/tool-dependencies/htseq/0.6.1/iuc/package_htseq_0_6/fbb72996807d
```

**Comment by gregvonkuster** [comment] 2015-07-28 15:18
@lparsons @bgruening Ah, I was focused on installation, not tool runtime.  I'm not quite sure of the current status of the Galaxy framework for defining the environment at tool runtime with regard to handling all dependencies.  Sorry about my confusion on this!

**Comment by lparsons** [comment] 2015-07-28 15:31
@gregvonkuster @bgruening Any thoughts on a quick fix for this for at least the htseq-count tool? I'm thinking at the moment, I could just manually add the LD_LIBRARY_PATH lines into the package_htseq_0_6 env.sh file, but that won't fix it for anyone else.

Alternatively, I could add atlas as a dependency to the htseq-count tool itself (or more appropriately, the package_hteq_0_6 package, but I can't actually update that one) and add these lines to the tool_dependencies.xml file:
```
<environment_variable action="prepend_to" name="LD_LIBRARY_PATH">$ENV[ATLAS_LIB_DIR]</environment_variable>
<environment_variable action="prepend_to" name="LD_LIBRARY_PATH">$ENV[ATLAS_LIB_DIR]/atlas</environment_variable>
```

**Comment by bgruening** [comment] 2015-07-28 17:26
Ok, we found a interim solution to depend on numpy to get all the ENV correct.

@gregvonkuster @blankenberg can you please comment on the idea to link every compile time dependency automatically (without specifying them in `set_environment`) to the env.sh file.
In the case of this issue we simple source `numpy` before sourcing `htseq`. And actually before `numpy` we are sourcing `atlas`. Does anyone has a counter argument for this? This would simplify tool dependencies a lot. Also see here: https://trello.com/c/lLoJ6vfe/244-simplify-environment-settings-in-tool-dependency-recipes

**Comment by lparsons** [comment] 2015-07-28 17:39
I second what @bgruening said, recursively sourcing dependency env.sh files at runtime would greatly simplify tool development. As it is now, any tool that requires `package_htseq_0_6` needs to know that it also needs to define a dependency on numpy 1.7.1 from `package_numpy_1_7` by `iuc`. See lparsons/galaxy_tools@23de2bdafad4d386cfe88724c0e6f93a70fdb84e

**Comment by gregvonkuster** [comment] 2015-07-28 17:45
@bgruening @blankenberg @lparsons  I think it would be good to provide the ability to source all necessary/required package env.sh files at tool run-time much like is currently done at package compile time.  Recursively sourcing env.sh files may be the simplest solution for this problem, but I cannot make the best call on this.

**Comment by lparsons** [comment] 2015-10-13 13:48
Just an FYI, once again I am running into this issue (this time using deeptools) on my production galaxy. Each reboot seems to generate new behavior with dependencies, and I go through various gyrations of uninstalling, reinstalling, restarting, etc. until it's fixed, but inevitably, something else will break. I think I need to go through the various places that can get out of sync with dependencies (database, config files, tool dependency directories, etc.) and try to find out what is happening. Ugh.

**Comment by lparsons** [comment] 2015-10-16 17:03
Just to put this in writing somewhere, my new issues were due to a disconnect between the revision of various installed "package_*" repositories and the revisions referred to in env.sh files for deeptools and other installed tools that depended on those packages. This is likely due to uninstall and reinstallation required to fix various installation bugs, etc. I do believe that there could be some improvement to the robustness of handling various revisions of "package_*" repositories, though I haven't thought through everything yet. Perhaps as a first step/interim solution a script that checked various pieces of a Galaxy install for consistency (database records, config files, env.sh scripts, etc.).

**Comment by bgruening** [comment] 2015-10-16 17:08
@lparsons are you installing from the TTS or TS?
Just curious because I'm searching for testers of deeptools: https://testtoolshed.g2.bx.psu.edu/view/iuc/package_python_2_7_deeptools_1_5_11/ff7a945199fa

**Comment by lparsons** [comment] 2015-10-16 20:17
@bgruening This has been on production, so TS. I'm assuming you're looking for testing beyond just the Docker version of Galaxy?

**Comment by bgruening** [comment] 2015-10-16 20:29
Would be ideal. This is based on an complete new scientific Python stack with hopefully way less pain.
Everything is bound to one specific Python version.

**Comment by gregvonkuster** [comment] 2015-10-17 13:08
@bgruening @lparsons Maybe a good option for the baseline scientific Python stack is Continuum's Anaconda Python.  The Python 2.7 version comes pre-built with this list of packages, so no dependency recipes are necessary.
http://docs.continuum.io/anaconda/pkg-docs.  
There are similar package lists for Python 3.
Also, adding new packages to the stack is easy using the conda command which comes with the Anaconda installation:

conda install -c https://conda.anaconda.org/anaconda <package name>
