### ISSUE TITLE
Metaphlan showing metadata error!

### ISSUE THREAD

**Issue by subinamehta** [galaxyproject/tools-iuc#2353] opened 2019-04-03 13:34 UTC
I have been trying to run Metaphlan on my data and it keeps giving me this error. The Metaphlan tool provides 3 output ( Community profile, SAM file and BIOM file). The community Profile has output but the tool has failed showing this error. Could you please look into this?

Fatal error: 
ERROR:galaxy.datatypes.text:Something in the metadata detection for biom1 went wrong.
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/datatypes/text.py", line 259, in set_meta
    for k, v in column['metadata'].items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by nsoranzo** [comment] 2019-04-03 13:40
Duplicate of https://github.com/galaxyproject/galaxy/issues/7625

**Closed by nsoranzo** 2019-04-03 13:40 UTC
