### ISSUE TITLE
package_htseq_0_6 doesn't set LD_LIBRARY_PATH for Atlas

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#221] opened 2015-07-24 19:41 UTC
The package requires numpy, and does seem to set the numpy path correctly, but does not ever set `LD_LIBRARY_PATH` which means that atlas is not found (see #104). It seems rather onerous to require packages that need numpy to remember to set the `LD_LIBRARY_PATH` explicitly (or any path for that matter), is this how it's supposed to work?

**Comment by bgruening** [comment] 2015-07-24 19:47
@lparsons can you check if this solves your problem. https://github.com/galaxyproject/galaxy/pull/403/files
It took us a while to track this down, but at least for me it fixes this issue.

**Comment by lparsons** [comment] 2015-07-24 19:54
@bgruening Sure, I've applied that change and restarted. Now I suppose I need to uninstall and reinstall some things? Which should I uninstall and reinstall?

**Comment by bgruening** [comment] 2015-07-24 19:55
Yes you do :( Sorry. Begin with the child of the dependency tree ... atlas, numpy, ... sorry.

**Comment by gregvonkuster** [comment] 2015-07-24 19:59
I’ve found that in some cases I’ve needed the following chang to the package_atlas_3_10 recipe.  I have not submitted a pull request for the patch because I’m still in the process of ironing out my recipes and (until now) I was not aware of anyone else bumping into this issue, so I figured it may just be “me doing something wrong”. 

diff --git a/packages/package_atlas_3_10/tool_dependencies.xml b/packages/package_atlas_3_10/tool_dependencies.xml
index e1cb3cd..8069c7e 100644
--- a/packages/package_atlas_3_10/tool_dependencies.xml
+++ b/packages/package_atlas_3_10/tool_dependencies.xml
@@ -8,6 +8,9 @@
                         <source_directory>.</source_directory>
                         <destination_directory>$INSTALL_DIR</destination_directory>
                     </action>
+                    <action type="shell_command">
+                        export ATLAS_LIB_DIR=$INSTALL_DIR/lib &amp;&amp;
+                    </action>
                     <action type="set_environment">
                         <environment_variable action="set_to" name="ATLAS_LIB_DIR">$INSTALL_DIR/lib</environment_variable>
                         <environment_variable action="set_to" name="ATLAS_INCLUDE_DIR">$INSTALL_DIR/include</environment_variable>
@@ -44,6 +47,7 @@
                     <action type="shell_command">tar -jxvf atlas3.10.2.tar.bz2</action>
                     
                     <action type="shell_command"><![CDATA[
+                        export ATLAS_LIB_DIR=$INSTALL_DIR/lib &&
                         cd ATLAS &&
                         mkdir ATLAS/build &&
                         patch -p1 </host/static_full_blas_lapack.diff &&




The tool_dependencies.xl file for pacage_htseq_count_0_6 at https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_htseq_0_6 <https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_htseq_0_6> contains this:

                <action type="set_environment_for_install">
                    <repository name="package_numpy_1_7" owner="iuc">
                        <package name="numpy" version="1.7.1" />
                    </repository>

And the tool_dependencies.xml file for package_numpy_1_7 available at  https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_numpy_1_7/tool_dependencies.xml <https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_numpy_1_7/tool_dependencies.xml> contains this:

        <package name="atlas" version="3.10.2">
            <repository name="package_atlas_3_10" owner="iuc" prior_installation_required="True" />
        </package>



and this:


		    <action type="shell_command">
		      cat &gt; site.cfg &lt;&lt;EOF
[DEFAULT]
library_dirs = $ATLAS_LIB_DIR
include_dirs = $ATLAS_INCLUDE_DIR
[blas_opt]
libraries = blas, atlas
[lapack_opt]
libraries = lapack, atlas
EOF
		    </action>


So could these packages as well as some others require the above patch to the atlas package as well?

**Comment by lparsons** [comment] 2015-07-24 20:04
Hmmm, I was hoping that galaxyproject/galaxy#403 would negate the need for explicitly setting the LD_LIBRARY_PATH in every package that uses numpy. It seems wrong that I can't just require a dependency and get the proper environment set...

**Comment by bgruening** [comment] 2015-07-24 20:06
> ```<action type="shell_command"> export ATLAS_LIB_DIR=$INSTALL_DIR/lib &amp;&amp; </action>```

Does this work? I thought `shell_command` is atomic and does not influence other commands. like `cd /some/dir` will not change dir directory for all other commands.

**Comment by lparsons** [comment] 2015-07-24 20:07
Also, it seems like the toolshed is no longer running tests. Seems like that would have helped find this long ago in this case...

**Comment by bgruening** [comment] 2015-07-24 20:08
> Hmmm, I was hoping that galaxyproject/galaxy#403 would negate the need for explicitly setting the LD_LIBRARY_PATH in every package that uses numpy. It seems wrong that I can't just require a dependency and get the proper environment set ...

You mean automatically set all `set_environment_for_install` for the current package? We discussed this afaik, but currently it is not implemented.

**Comment by lparsons** [comment] 2015-07-24 20:09
No, I mean source the `env.sh` file for the required package and all dependencies prior to tool execution.

**Comment by lparsons** [comment] 2015-07-24 20:12
That being said, things seem to be improved now after the patch. Still testing.

**Comment by bgruening** [comment] 2015-07-24 20:12
> Also, it seems like the toolshed is no longer running tests. Seems like that would have helped find this long ago in this case...
@lparsons True :( but this decision was above my pay grade

 >No, I mean source the `env.sh` file for the required package and all dependencies prior to tool execution.
I guess this boils down to the same thing. You want to have all libraries that are needed at runtime in your env.sh file which you require in your tool.
Imho, this can be done by simply linking all env.sh files that are imported during `set_environment_for_install` into the package env.sh file. @gregvonkuster what do you think?

**Comment by bgruening** [comment] 2015-07-24 20:16
@gregvonkuster That being said, I don't mind to include this export. I don't think so many users running Galaxy and TS install under OS-X. So this can be likely a problem.

**Comment by lparsons** [comment] 2015-07-24 20:24
I don't mind including the export, however, I do think it's a bit much to ask tool developers to look at all of the dependencies of dependencies to figure out what things to include in the environment. Also, I'm **strongly** in favor of better continuous testing (under at least a couple of different systems). I've run into far too many errors that could have been caught with simple tests (and I've spent too much time writing tests to have them unused).

**Comment by bgruening** [comment] 2015-07-24 20:27
@lparsons the idea is to have this tested by planemo really soon, afaik. So the test framework is only temporary disabled.

**Comment by lparsons** [comment] 2015-07-24 20:31
@bgruening Fantastic! Thanks for help. @gregvonkuster I'd like to make sure these issues are fixed, so if patches are needed to repos, please let me know ASAP so I can get things back into shape. Much appreciated.

**Comment by bgruening** [comment] 2015-07-24 20:32
@lparsons all the credit belongs to @gregvonkuster !

**Comment by gregvonkuster** [comment] 2015-07-27 11:57
@bgruening @lparsons let's hold off on changing the atlas package for now.  After a bit more thought on this, I have a feeling the additional exports I needed were necessary only because I had not yet uncovered and fixed this https://github.com/galaxyproject/galaxy/pull/403 at the time I found them to be necessary.  I'm currently working on some fairly complex recipes that install numpy which requires atlas, so I'll confirm that atlas is working.

@bgruening regarding your statement: "I thought shell_command is atomic and does not influence other commands. like cd /some/dir will not change dir directory for all other commands."

I believe the "shell_command" action type is atomic (although maybe some things done in a shell could influence later shell environments) - I could be wrong on this.  It's probably likely that those exports were not what got things working for me - I was working on this several weeks ago, so I'm not quite sure.  I had a lot of things going, and it's more likely that my uncovering and fixing the problem in the above pull request was actually what got things working for me.  Again, I'll confirm, and let you know if anything needs to be changed with the atlas recipe.

**Comment by lparsons** [comment] 2015-07-27 14:58
@gregvonkuster @bgruening I believe you are correct and the atlas exports are no longer necessary after the this fix in galaxyproject/galaxy#403. Thanks so much @gregvonkuster, I'm fairly sure this issue has been plaguing me for a long time... :smile:

**Comment by lparsons** [comment] 2015-07-28 14:07
@gregvonkuster @bgruening Unfortunately this issue is still present in my system. I'm going to have to revert to the older htseq-count for the time being.

**Comment by bgruening** [comment] 2015-10-02 19:20
@lparsons is this still valid? How can I help you here, can you give me a Docker flavour or guide so that I can reproduce it?

**Comment by lparsons** [comment] 2015-10-05 19:24
I believe this was "resolved" by adding Numpy as a dependency to tools that depend on htseq (htseq-count). The discussion probably happened over IRC, sorry for not updating here. See https://github.com/lparsons/galaxy_tools/commit/23de2bdafad4d386cfe88724c0e6f93a70fdb84e and https://trello.com/c/lLoJ6vfe.

**Comment by bgruening** [comment] 2015-10-05 19:31
Great will close this.

**Closed by bgruening** 2015-10-05 19:31 UTC
Labels: bug
